create table machine_typekpi
(
    machine_kpi_id  bigint generated by default as identity
        primary key,
    kpi_id          bigint
        constraint fkj4d8j9pvxg4e2qx7slcebmblh
            references kpi,
    machine_type_id bigint
        constraint fks6olk5bqnjdo8ehxr9ful02ww
            references machine_type
);

alter table machine_typekpi
    owner to postgres;

