create table kpicategory
(
    category_id bigint generated by default as identity
        primary key,
    description varchar(255),
    name        varchar(255)
);

alter table kpicategory
    owner to postgres;

create table kpi
(
    kpi_id      bigint generated by default as identity
        primary key,
    description varchar(255),
    formula     varchar(255),
    frequency   varchar(255),
    has_formula boolean not null,
    name        varchar(255),
    units       varchar(255),
    category_id bigint
        constraint fkell79cjceouhln7eiqojhsnfa
            references kpicategory
);

alter table kpi
    owner to postgres;

create table alert
(
    alert_id  bigint generated by default as identity
        primary key,
    action    varchar(255),
    condition varchar(255),
    priority  integer not null,
    kpi_id    bigint
        constraint fk7b9nud8c8qqmewacvdhv0qcxo
            references kpi
);

alter table alert
    owner to postgres;

create table kpi_dependencies
(
    kpi_id           bigint not null
        constraint fkemi5ve67r7jydhsfftja5e3pc
            references kpi,
    dependent_kpi_id bigint not null
        constraint fk7403pi3kgttfkb2d11nagxhh
            references kpi
);

alter table kpi_dependencies
    owner to postgres;

create table machine_type
(
    machine_type_id bigint generated by default as identity
        primary key,
    description     varchar(255),
    type_name       varchar(255)
);

alter table machine_type
    owner to postgres;

create table site
(
    site_id  bigint generated by default as identity
        primary key,
    location varchar(255)
);

alter table site
    owner to postgres;

create table machine
(
    machine_id   bigint generated by default as identity
        primary key,
    asset_id     varchar(255),
    install_date varchar(255),
    machine_type varchar(255),
    name         varchar(255),
    site_id      bigint
        constraint fk37cwo146a4fm1u5rw94gercii
            references site,
    type_id      bigint
        constraint fkorr84bibxjy4mc4fw56qfv6dm
            references machine_type
);

alter table machine
    owner to postgres;

create table threshold
(
    threshold_id bigint generated by default as identity
        primary key,
    average      double precision,
    maximum      double precision,
    minimum      double precision,
    sum          double precision,
    kpi_id       bigint
        constraint fksq5048g0s71ay1i6u1hg8loj4
            references kpi,
    machine_id   bigint
        constraint fk3vs94wmxam41uld6ahv5v782u
            references machine
);

alter table threshold
    owner to postgres;

