# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ai_response_report_sections import AIResponseReportSections  # noqa: F401,E501
from swagger_server import util


class AIResponseReport(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, sections: AIResponseReportSections=None):  # noqa: E501
        """AIResponseReport - a model defined in Swagger

        :param title: The title of this AIResponseReport.  # noqa: E501
        :type title: str
        :param sections: The sections of this AIResponseReport.  # noqa: E501
        :type sections: AIResponseReportSections
        """
        self.swagger_types = {
            'title': str,
            'sections': AIResponseReportSections
        }

        self.attribute_map = {
            'title': 'title',
            'sections': 'sections'
        }
        self._title = title
        self._sections = sections

    @classmethod
    def from_dict(cls, dikt) -> 'AIResponseReport':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AIResponse_report of this AIResponseReport.  # noqa: E501
        :rtype: AIResponseReport
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this AIResponseReport.


        :return: The title of this AIResponseReport.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this AIResponseReport.


        :param title: The title of this AIResponseReport.
        :type title: str
        """

        self._title = title

    @property
    def sections(self) -> AIResponseReportSections:
        """Gets the sections of this AIResponseReport.


        :return: The sections of this AIResponseReport.
        :rtype: AIResponseReportSections
        """
        return self._sections

    @sections.setter
    def sections(self, sections: AIResponseReportSections):
        """Sets the sections of this AIResponseReport.


        :param sections: The sections of this AIResponseReport.
        :type sections: AIResponseReportSections
        """

        self._sections = sections
