# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AIResponseGraphData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, keys: List[str]=None, values: List[float]=None):  # noqa: E501
        """AIResponseGraphData - a model defined in Swagger

        :param keys: The keys of this AIResponseGraphData.  # noqa: E501
        :type keys: List[str]
        :param values: The values of this AIResponseGraphData.  # noqa: E501
        :type values: List[float]
        """
        self.swagger_types = {
            'keys': List[str],
            'values': List[float]
        }

        self.attribute_map = {
            'keys': 'keys',
            'values': 'values'
        }
        self._keys = keys
        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'AIResponseGraphData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AIResponse_graph_data of this AIResponseGraphData.  # noqa: E501
        :rtype: AIResponseGraphData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def keys(self) -> List[str]:
        """Gets the keys of this AIResponseGraphData.


        :return: The keys of this AIResponseGraphData.
        :rtype: List[str]
        """
        return self._keys

    @keys.setter
    def keys(self, keys: List[str]):
        """Sets the keys of this AIResponseGraphData.


        :param keys: The keys of this AIResponseGraphData.
        :type keys: List[str]
        """

        self._keys = keys

    @property
    def values(self) -> List[float]:
        """Gets the values of this AIResponseGraphData.


        :return: The values of this AIResponseGraphData.
        :rtype: List[float]
        """
        return self._values

    @values.setter
    def values(self, values: List[float]):
        """Sets the values of this AIResponseGraphData.


        :param values: The values of this AIResponseGraphData.
        :type values: List[float]
        """

        self._values = values
