# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ai_response_graph_data import AIResponseGraphData  # noqa: F401,E501
from swagger_server import util


class AIResponseGraph(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, data: AIResponseGraphData=None):  # noqa: E501
        """AIResponseGraph - a model defined in Swagger

        :param type: The type of this AIResponseGraph.  # noqa: E501
        :type type: str
        :param data: The data of this AIResponseGraph.  # noqa: E501
        :type data: AIResponseGraphData
        """
        self.swagger_types = {
            'type': str,
            'data': AIResponseGraphData
        }

        self.attribute_map = {
            'type': 'type',
            'data': 'data'
        }
        self._type = type
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'AIResponseGraph':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AIResponse_graph of this AIResponseGraph.  # noqa: E501
        :rtype: AIResponseGraph
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this AIResponseGraph.


        :return: The type of this AIResponseGraph.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this AIResponseGraph.


        :param type: The type of this AIResponseGraph.
        :type type: str
        """
        allowed_values = ["pie", "bar"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def data(self) -> AIResponseGraphData:
        """Gets the data of this AIResponseGraph.


        :return: The data of this AIResponseGraph.
        :rtype: AIResponseGraphData
        """
        return self._data

    @data.setter
    def data(self, data: AIResponseGraphData):
        """Sets the data of this AIResponseGraph.


        :param data: The data of this AIResponseGraph.
        :type data: AIResponseGraphData
        """

        self._data = data
