# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AIResponseDashboardValues(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, x: date=None, y: int=None):  # noqa: E501
        """AIResponseDashboardValues - a model defined in Swagger

        :param x: The x of this AIResponseDashboardValues.  # noqa: E501
        :type x: date
        :param y: The y of this AIResponseDashboardValues.  # noqa: E501
        :type y: int
        """
        self.swagger_types = {
            'x': date,
            'y': int
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y'
        }
        self._x = x
        self._y = y

    @classmethod
    def from_dict(cls, dikt) -> 'AIResponseDashboardValues':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AIResponse_dashboard_values of this AIResponseDashboardValues.  # noqa: E501
        :rtype: AIResponseDashboardValues
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self) -> date:
        """Gets the x of this AIResponseDashboardValues.


        :return: The x of this AIResponseDashboardValues.
        :rtype: date
        """
        return self._x

    @x.setter
    def x(self, x: date):
        """Sets the x of this AIResponseDashboardValues.


        :param x: The x of this AIResponseDashboardValues.
        :type x: date
        """

        self._x = x

    @property
    def y(self) -> int:
        """Gets the y of this AIResponseDashboardValues.


        :return: The y of this AIResponseDashboardValues.
        :rtype: int
        """
        return self._y

    @y.setter
    def y(self, y: int):
        """Sets the y of this AIResponseDashboardValues.


        :param y: The y of this AIResponseDashboardValues.
        :type y: int
        """

        self._y = y
