# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.one_of_ai_response_dashboard_values import OneOfAIResponseDashboardValues  # noqa: F401,E501
from swagger_server import util


class AIResponseDashboard(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, x_axis_name: str=None, y_axis_name: str=None, values: OneOfAIResponseDashboardValues=None):  # noqa: E501
        """AIResponseDashboard - a model defined in Swagger

        :param x_axis_name: The x_axis_name of this AIResponseDashboard.  # noqa: E501
        :type x_axis_name: str
        :param y_axis_name: The y_axis_name of this AIResponseDashboard.  # noqa: E501
        :type y_axis_name: str
        :param values: The values of this AIResponseDashboard.  # noqa: E501
        :type values: OneOfAIResponseDashboardValues
        """
        self.swagger_types = {
            'x_axis_name': str,
            'y_axis_name': str,
            'values': OneOfAIResponseDashboardValues
        }

        self.attribute_map = {
            'x_axis_name': 'x_axis_name',
            'y_axis_name': 'y_axis_name',
            'values': 'values'
        }
        self._x_axis_name = x_axis_name
        self._y_axis_name = y_axis_name
        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'AIResponseDashboard':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AIResponse_dashboard of this AIResponseDashboard.  # noqa: E501
        :rtype: AIResponseDashboard
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x_axis_name(self) -> str:
        """Gets the x_axis_name of this AIResponseDashboard.


        :return: The x_axis_name of this AIResponseDashboard.
        :rtype: str
        """
        return self._x_axis_name

    @x_axis_name.setter
    def x_axis_name(self, x_axis_name: str):
        """Sets the x_axis_name of this AIResponseDashboard.


        :param x_axis_name: The x_axis_name of this AIResponseDashboard.
        :type x_axis_name: str
        """

        self._x_axis_name = x_axis_name

    @property
    def y_axis_name(self) -> str:
        """Gets the y_axis_name of this AIResponseDashboard.


        :return: The y_axis_name of this AIResponseDashboard.
        :rtype: str
        """
        return self._y_axis_name

    @y_axis_name.setter
    def y_axis_name(self, y_axis_name: str):
        """Sets the y_axis_name of this AIResponseDashboard.


        :param y_axis_name: The y_axis_name of this AIResponseDashboard.
        :type y_axis_name: str
        """

        self._y_axis_name = y_axis_name

    @property
    def values(self) -> OneOfAIResponseDashboardValues:
        """Gets the values of this AIResponseDashboard.


        :return: The values of this AIResponseDashboard.
        :rtype: OneOfAIResponseDashboardValues
        """
        return self._values

    @values.setter
    def values(self, values: OneOfAIResponseDashboardValues):
        """Sets the values of this AIResponseDashboard.


        :param values: The values of this AIResponseDashboard.
        :type values: OneOfAIResponseDashboardValues
        """

        self._values = values
