# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.id import ID  # noqa: F401,E501
from swagger_server.models.machine_status import MachineStatus  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: ID=None, status: MachineStatus=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param id: The id of this InlineResponse200.  # noqa: E501
        :type id: ID
        :param status: The status of this InlineResponse200.  # noqa: E501
        :type status: MachineStatus
        """
        self.swagger_types = {
            'id': ID,
            'status': MachineStatus
        }

        self.attribute_map = {
            'id': 'id',
            'status': 'status'
        }
        self._id = id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> ID:
        """Gets the id of this InlineResponse200.


        :return: The id of this InlineResponse200.
        :rtype: ID
        """
        return self._id

    @id.setter
    def id(self, id: ID):
        """Sets the id of this InlineResponse200.


        :param id: The id of this InlineResponse200.
        :type id: ID
        """

        self._id = id

    @property
    def status(self) -> MachineStatus:
        """Gets the status of this InlineResponse200.


        :return: The status of this InlineResponse200.
        :rtype: MachineStatus
        """
        return self._status

    @status.setter
    def status(self, status: MachineStatus):
        """Sets the status of this InlineResponse200.


        :param status: The status of this InlineResponse200.
        :type status: MachineStatus
        """

        self._status = status
