# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.id import ID  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ids: List[ID]=None, names: List[str]=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param ids: The ids of this InlineResponse2001.  # noqa: E501
        :type ids: List[ID]
        :param names: The names of this InlineResponse2001.  # noqa: E501
        :type names: List[str]
        """
        self.swagger_types = {
            'ids': List[ID],
            'names': List[str]
        }

        self.attribute_map = {
            'ids': 'ids',
            'names': 'names'
        }
        self._ids = ids
        self._names = names

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ids(self) -> List[ID]:
        """Gets the ids of this InlineResponse2001.


        :return: The ids of this InlineResponse2001.
        :rtype: List[ID]
        """
        return self._ids

    @ids.setter
    def ids(self, ids: List[ID]):
        """Sets the ids of this InlineResponse2001.


        :param ids: The ids of this InlineResponse2001.
        :type ids: List[ID]
        """

        self._ids = ids

    @property
    def names(self) -> List[str]:
        """Gets the names of this InlineResponse2001.


        :return: The names of this InlineResponse2001.
        :rtype: List[str]
        """
        return self._names

    @names.setter
    def names(self, names: List[str]):
        """Sets the names of this InlineResponse2001.


        :param names: The names of this InlineResponse2001.
        :type names: List[str]
        """

        self._names = names
