# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.id import ID  # noqa: F401,E501
from swagger_server.models.machine_basic_info import MachineBasicInfo  # noqa: F401,E501
from swagger_server.models.machine_status import MachineStatus  # noqa: F401,E501
from swagger_server import util


class MachineCompleteInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: ID=None, machine_type: str=None, production_line: int=None, factory: str=None, name: str=None, status: MachineStatus=None):  # noqa: E501
        """MachineCompleteInfo - a model defined in Swagger

        :param id: The id of this MachineCompleteInfo.  # noqa: E501
        :type id: ID
        :param machine_type: The machine_type of this MachineCompleteInfo.  # noqa: E501
        :type machine_type: str
        :param production_line: The production_line of this MachineCompleteInfo.  # noqa: E501
        :type production_line: int
        :param factory: The factory of this MachineCompleteInfo.  # noqa: E501
        :type factory: str
        :param name: The name of this MachineCompleteInfo.  # noqa: E501
        :type name: str
        :param status: The status of this MachineCompleteInfo.  # noqa: E501
        :type status: MachineStatus
        """
        self.swagger_types = {
            'id': ID,
            'machine_type': str,
            'production_line': int,
            'factory': str,
            'name': str,
            'status': MachineStatus
        }

        self.attribute_map = {
            'id': 'id',
            'machine_type': 'machineType',
            'production_line': 'productionLine',
            'factory': 'factory',
            'name': 'name',
            'status': 'status'
        }
        self._id = id
        self._machine_type = machine_type
        self._production_line = production_line
        self._factory = factory
        self._name = name
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'MachineCompleteInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineCompleteInfo of this MachineCompleteInfo.  # noqa: E501
        :rtype: MachineCompleteInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> ID:
        """Gets the id of this MachineCompleteInfo.


        :return: The id of this MachineCompleteInfo.
        :rtype: ID
        """
        return self._id

    @id.setter
    def id(self, id: ID):
        """Sets the id of this MachineCompleteInfo.


        :param id: The id of this MachineCompleteInfo.
        :type id: ID
        """

        self._id = id

    @property
    def machine_type(self) -> str:
        """Gets the machine_type of this MachineCompleteInfo.


        :return: The machine_type of this MachineCompleteInfo.
        :rtype: str
        """
        return self._machine_type

    @machine_type.setter
    def machine_type(self, machine_type: str):
        """Sets the machine_type of this MachineCompleteInfo.


        :param machine_type: The machine_type of this MachineCompleteInfo.
        :type machine_type: str
        """

        self._machine_type = machine_type

    @property
    def production_line(self) -> int:
        """Gets the production_line of this MachineCompleteInfo.


        :return: The production_line of this MachineCompleteInfo.
        :rtype: int
        """
        return self._production_line

    @production_line.setter
    def production_line(self, production_line: int):
        """Sets the production_line of this MachineCompleteInfo.


        :param production_line: The production_line of this MachineCompleteInfo.
        :type production_line: int
        """

        self._production_line = production_line

    @property
    def factory(self) -> str:
        """Gets the factory of this MachineCompleteInfo.


        :return: The factory of this MachineCompleteInfo.
        :rtype: str
        """
        return self._factory

    @factory.setter
    def factory(self, factory: str):
        """Sets the factory of this MachineCompleteInfo.


        :param factory: The factory of this MachineCompleteInfo.
        :type factory: str
        """

        self._factory = factory

    @property
    def name(self) -> str:
        """Gets the name of this MachineCompleteInfo.


        :return: The name of this MachineCompleteInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MachineCompleteInfo.


        :param name: The name of this MachineCompleteInfo.
        :type name: str
        """

        self._name = name

    @property
    def status(self) -> MachineStatus:
        """Gets the status of this MachineCompleteInfo.


        :return: The status of this MachineCompleteInfo.
        :rtype: MachineStatus
        """
        return self._status

    @status.setter
    def status(self, status: MachineStatus):
        """Sets the status of this MachineCompleteInfo.


        :param status: The status of this MachineCompleteInfo.
        :type status: MachineStatus
        """

        self._status = status
