# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MachineKPIValuesValues(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, start_date: str=None, end_date: str=None, value: float=None):  # noqa: E501
        """MachineKPIValuesValues - a model defined in Swagger

        :param start_date: The start_date of this MachineKPIValuesValues.  # noqa: E501
        :type start_date: str
        :param end_date: The end_date of this MachineKPIValuesValues.  # noqa: E501
        :type end_date: str
        :param value: The value of this MachineKPIValuesValues.  # noqa: E501
        :type value: float
        """
        self.swagger_types = {
            'start_date': str,
            'end_date': str,
            'value': float
        }

        self.attribute_map = {
            'start_date': 'startDate',
            'end_date': 'endDate',
            'value': 'value'
        }
        self._start_date = start_date
        self._end_date = end_date
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'MachineKPIValuesValues':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineKPIValues_values of this MachineKPIValuesValues.  # noqa: E501
        :rtype: MachineKPIValuesValues
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_date(self) -> str:
        """Gets the start_date of this MachineKPIValuesValues.


        :return: The start_date of this MachineKPIValuesValues.
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: str):
        """Sets the start_date of this MachineKPIValuesValues.


        :param start_date: The start_date of this MachineKPIValuesValues.
        :type start_date: str
        """

        self._start_date = start_date

    @property
    def end_date(self) -> str:
        """Gets the end_date of this MachineKPIValuesValues.


        :return: The end_date of this MachineKPIValuesValues.
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: str):
        """Sets the end_date of this MachineKPIValuesValues.


        :param end_date: The end_date of this MachineKPIValuesValues.
        :type end_date: str
        """

        self._end_date = end_date

    @property
    def value(self) -> float:
        """Gets the value of this MachineKPIValuesValues.


        :return: The value of this MachineKPIValuesValues.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this MachineKPIValuesValues.


        :param value: The value of this MachineKPIValuesValues.
        :type value: float
        """

        self._value = value
