# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.id import ID  # noqa: F401,E501
from swagger_server import util


class MachineXKPIInfoRelation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, machine_id: ID=None, kpi_id: ID=None):  # noqa: E501
        """MachineXKPIInfoRelation - a model defined in Swagger

        :param machine_id: The machine_id of this MachineXKPIInfoRelation.  # noqa: E501
        :type machine_id: ID
        :param kpi_id: The kpi_id of this MachineXKPIInfoRelation.  # noqa: E501
        :type kpi_id: ID
        """
        self.swagger_types = {
            'machine_id': ID,
            'kpi_id': ID
        }

        self.attribute_map = {
            'machine_id': 'machineID',
            'kpi_id': 'kpiID'
        }
        self._machine_id = machine_id
        self._kpi_id = kpi_id

    @classmethod
    def from_dict(cls, dikt) -> 'MachineXKPIInfoRelation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineXKPIInfo_relation of this MachineXKPIInfoRelation.  # noqa: E501
        :rtype: MachineXKPIInfoRelation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def machine_id(self) -> ID:
        """Gets the machine_id of this MachineXKPIInfoRelation.


        :return: The machine_id of this MachineXKPIInfoRelation.
        :rtype: ID
        """
        return self._machine_id

    @machine_id.setter
    def machine_id(self, machine_id: ID):
        """Sets the machine_id of this MachineXKPIInfoRelation.


        :param machine_id: The machine_id of this MachineXKPIInfoRelation.
        :type machine_id: ID
        """

        self._machine_id = machine_id

    @property
    def kpi_id(self) -> ID:
        """Gets the kpi_id of this MachineXKPIInfoRelation.


        :return: The kpi_id of this MachineXKPIInfoRelation.
        :rtype: ID
        """
        return self._kpi_id

    @kpi_id.setter
    def kpi_id(self, kpi_id: ID):
        """Sets the kpi_id of this MachineXKPIInfoRelation.


        :param kpi_id: The kpi_id of this MachineXKPIInfoRelation.
        :type kpi_id: ID
        """

        self._kpi_id = kpi_id
