# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MachineKPIInfoSeries(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, time_interval: str=None, value: float=None):  # noqa: E501
        """MachineKPIInfoSeries - a model defined in Swagger

        :param time_interval: The time_interval of this MachineKPIInfoSeries.  # noqa: E501
        :type time_interval: str
        :param value: The value of this MachineKPIInfoSeries.  # noqa: E501
        :type value: float
        """
        self.swagger_types = {
            'time_interval': str,
            'value': float
        }

        self.attribute_map = {
            'time_interval': 'timeInterval',
            'value': 'value'
        }
        self._time_interval = time_interval
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'MachineKPIInfoSeries':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineKPIInfo_series of this MachineKPIInfoSeries.  # noqa: E501
        :rtype: MachineKPIInfoSeries
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_interval(self) -> str:
        """Gets the time_interval of this MachineKPIInfoSeries.

        interval related to the value  # noqa: E501

        :return: The time_interval of this MachineKPIInfoSeries.
        :rtype: str
        """
        return self._time_interval

    @time_interval.setter
    def time_interval(self, time_interval: str):
        """Sets the time_interval of this MachineKPIInfoSeries.

        interval related to the value  # noqa: E501

        :param time_interval: The time_interval of this MachineKPIInfoSeries.
        :type time_interval: str
        """

        self._time_interval = time_interval

    @property
    def value(self) -> float:
        """Gets the value of this MachineKPIInfoSeries.


        :return: The value of this MachineKPIInfoSeries.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this MachineKPIInfoSeries.


        :param value: The value of this MachineKPIInfoSeries.
        :type value: float
        """

        self._value = value
