# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ReportHeader(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, creation_time: str=None, title: str=None):  # noqa: E501
        """ReportHeader - a model defined in Swagger

        :param id: The id of this ReportHeader.  # noqa: E501
        :type id: int
        :param creation_time: The creation_time of this ReportHeader.  # noqa: E501
        :type creation_time: str
        :param title: The title of this ReportHeader.  # noqa: E501
        :type title: str
        """
        self.swagger_types = {
            'id': int,
            'creation_time': str,
            'title': str
        }

        self.attribute_map = {
            'id': 'id',
            'creation_time': 'creationTime',
            'title': 'title'
        }
        self._id = id
        self._creation_time = creation_time
        self._title = title

    @classmethod
    def from_dict(cls, dikt) -> 'ReportHeader':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReportHeader of this ReportHeader.  # noqa: E501
        :rtype: ReportHeader
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ReportHeader.


        :return: The id of this ReportHeader.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ReportHeader.


        :param id: The id of this ReportHeader.
        :type id: int
        """

        self._id = id

    @property
    def creation_time(self) -> str:
        """Gets the creation_time of this ReportHeader.


        :return: The creation_time of this ReportHeader.
        :rtype: str
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time: str):
        """Sets the creation_time of this ReportHeader.


        :param creation_time: The creation_time of this ReportHeader.
        :type creation_time: str
        """

        self._creation_time = creation_time

    @property
    def title(self) -> str:
        """Gets the title of this ReportHeader.


        :return: The title of this ReportHeader.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this ReportHeader.


        :param title: The title of this ReportHeader.
        :type title: str
        """

        self._title = title
