# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.report_header import ReportHeader  # noqa: F401,E501
from swagger_server import util


class Report(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, header: ReportHeader=None, data: object=None):  # noqa: E501
        """Report - a model defined in Swagger

        :param header: The header of this Report.  # noqa: E501
        :type header: ReportHeader
        :param data: The data of this Report.  # noqa: E501
        :type data: object
        """
        self.swagger_types = {
            'header': ReportHeader,
            'data': object
        }

        self.attribute_map = {
            'header': 'header',
            'data': 'data'
        }
        self._header = header
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Report':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Report of this Report.  # noqa: E501
        :rtype: Report
        """
        return util.deserialize_model(dikt, cls)

    @property
    def header(self) -> ReportHeader:
        """Gets the header of this Report.


        :return: The header of this Report.
        :rtype: ReportHeader
        """
        return self._header

    @header.setter
    def header(self, header: ReportHeader):
        """Sets the header of this Report.


        :param header: The header of this Report.
        :type header: ReportHeader
        """

        self._header = header

    @property
    def data(self) -> object:
        """Gets the data of this Report.


        :return: The data of this Report.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this Report.


        :param data: The data of this Report.
        :type data: object
        """

        self._data = data
