# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.kpiid import KPIID  # noqa: F401,E501
from swagger_server import util


class SensorKPIItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, kpi: KPIID=None, value: float=None):  # noqa: E501
        """SensorKPIItem - a model defined in Swagger

        :param kpi: The kpi of this SensorKPIItem.  # noqa: E501
        :type kpi: KPIID
        :param value: The value of this SensorKPIItem.  # noqa: E501
        :type value: float
        """
        self.swagger_types = {
            'kpi': KPIID,
            'value': float
        }

        self.attribute_map = {
            'kpi': 'kpi',
            'value': 'value'
        }
        self._kpi = kpi
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'SensorKPIItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SensorKPIItem of this SensorKPIItem.  # noqa: E501
        :rtype: SensorKPIItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def kpi(self) -> KPIID:
        """Gets the kpi of this SensorKPIItem.


        :return: The kpi of this SensorKPIItem.
        :rtype: KPIID
        """
        return self._kpi

    @kpi.setter
    def kpi(self, kpi: KPIID):
        """Sets the kpi of this SensorKPIItem.


        :param kpi: The kpi of this SensorKPIItem.
        :type kpi: KPIID
        """

        self._kpi = kpi

    @property
    def value(self) -> float:
        """Gets the value of this SensorKPIItem.


        :return: The value of this SensorKPIItem.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this SensorKPIItem.


        :param value: The value of this SensorKPIItem.
        :type value: float
        """

        self._value = value
