# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserRole(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    FFM = "FFM"
    SMO = "SMO"
    SYSTEM = "System"
    def __init__(self):  # noqa: E501
        """UserRole - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'UserRole':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserRole of this UserRole.  # noqa: E501
        :rtype: UserRole
        """
        return util.deserialize_model(dikt, cls)
